import { db } from "./db";
import { clients, messages } from "@shared/schema";

async function seed() {
  console.log("🌱 Seeding database...");

  const [client] = await db.insert(clients).values({
    name: 'Burger King Local',
    industry: 'Restaurant',
    avatar: 'https://images.unsplash.com/photo-1561758033-d8f3c660b13c?w=100&h=100&fit=crop',
    agentName: 'BurgerBuddy',
    tone: 'funny',
    businessContext: 'We are a local franchise of a major burger chain.',
  }).returning();

  console.log("✅ Client created:", client.name);

  const mockMessages = [
    {
      clientId: client.id,
      platform: 'facebook',
      type: 'comment',
      author: 'AngryCustomer88',
      content: 'I waited 45 minutes for my order and it was COLD! This is unacceptable service. I want a refund immediately.',
      timestamp: new Date(Date.now() - 1000 * 60 * 5),
      status: 'unread',
      urgency: 'high',
      intent: 'complaint',
      sentiment: 'negative',
      aiSummary: 'Customer is angry about wait time and cold food. Demanding refund.',
      sourceUrl: 'https://facebook.com/post/123',
      contextType: 'post',
      crmData: null,
    },
    {
      clientId: client.id,
      platform: 'instagram',
      type: 'dm',
      author: '@burger_fan_sophie',
      content: 'Hey! Do you guys do catering for birthday parties? Looking for prices for about 20 people.',
      timestamp: new Date(Date.now() - 1000 * 60 * 15),
      status: 'unread',
      urgency: 'medium',
      intent: 'sales',
      sentiment: 'positive',
      aiSummary: 'Potential lead inquiring about catering pricing for an event.',
      contextType: 'dm',
      crmData: {
        crmId: 'hs_12345',
        crmType: 'hubspot',
        email: 'sophie@events.com',
        phone: '+1 (555) 987-6543',
        company: 'Sophie Events LLC',
        dealValue: 2500,
        dealStage: 'Discovery',
        lastNote: 'Interested in catering for 20 people. Sent initial menu.',
        profileUrl: 'https://app.hubspot.com/contacts/12345'
      },
    },
    {
      clientId: client.id,
      platform: 'youtube',
      type: 'comment',
      author: 'RandomViewer',
      content: 'First view! cool video.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60),
      status: 'unread',
      urgency: 'low',
      intent: 'general',
      sentiment: 'neutral',
      aiSummary: 'General engagement comment.',
      sourceUrl: 'https://youtube.com/watch?v=video123&lc=comment456',
      contextType: 'post',
      crmData: null,
    },
    {
      clientId: client.id,
      platform: 'linkedin',
      type: 'dm',
      author: 'Supplier Inc.',
      content: 'Hello, just checking if you received the invoice for the last shipment of buns?',
      timestamp: new Date(Date.now() - 1000 * 60 * 120),
      status: 'unread',
      urgency: 'medium',
      intent: 'support',
      sentiment: 'neutral',
      aiSummary: 'Vendor follow-up regarding invoice status.',
      contextType: 'dm',
      crmData: {
        crmId: 'hs_67890',
        crmType: 'hubspot',
        email: 'accounts@supplierinc.com',
        phone: '+1 (555) 111-2222',
        company: 'Supplier Inc.',
        dealValue: 10000,
        dealStage: 'Closed Won',
        lastNote: 'Invoice #4455 sent. Waiting for payment.',
        profileUrl: 'https://app.hubspot.com/contacts/67890'
      },
    },
    {
      clientId: client.id,
      platform: 'tiktok',
      type: 'comment',
      author: '@spicy_lover',
      content: 'Omg the new spicy sauce is EVERYTHING 🔥 Need to buy a bottle!',
      timestamp: new Date(Date.now() - 1000 * 60 * 180),
      status: 'unread',
      urgency: 'medium',
      intent: 'sales',
      sentiment: 'positive',
      aiSummary: 'Strong positive product feedback, potential upsell opportunity.',
      sourceUrl: 'https://tiktok.com/@user/video/789',
      contextType: 'post',
      crmData: null,
    },
    {
      clientId: client.id,
      platform: 'instagram',
      type: 'comment',
      author: '@picky_eater',
      content: 'The music was a bit loud yesterday.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
      status: 'unread',
      urgency: 'low',
      intent: 'complaint',
      sentiment: 'negative',
      aiSummary: 'Minor complaint about ambiance/volume.',
      sourceUrl: 'https://instagram.com/p/post321',
      contextType: 'post',
      crmData: null,
    },
    {
      clientId: client.id,
      platform: 'google-business',
      type: 'review',
      author: 'Local Guide Level 6',
      content: 'Great place, but parking is a nightmare during lunch hours.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
      status: 'unread',
      urgency: 'medium',
      intent: 'complaint',
      sentiment: 'neutral',
      aiSummary: 'Feedback about parking availability.',
      sourceUrl: 'https://goo.gl/maps/review123',
      contextType: 'post',
      crmData: null,
    },
    {
      clientId: client.id,
      platform: 'whatsapp',
      type: 'dm',
      author: '+1 555-0123',
      content: 'Hi, can I place an order for pickup via WhatsApp?',
      timestamp: new Date(Date.now() - 1000 * 60 * 10),
      status: 'unread',
      urgency: 'high',
      intent: 'sales',
      sentiment: 'positive',
      aiSummary: 'Direct order inquiry via WhatsApp.',
      contextType: 'dm',
      crmData: null,
    },
    {
      clientId: client.id,
      platform: 'facebook',
      type: 'dm',
      author: 'Mark Zuckerberg',
      content: 'We have a serious issue with the enterprise contract. Call me ASAP.',
      timestamp: new Date(Date.now() - 1000 * 60 * 2),
      status: 'unread',
      urgency: 'high',
      intent: 'support',
      sentiment: 'negative',
      aiSummary: 'Critical enterprise issue reported by high-profile user.',
      contextType: 'dm',
      crmData: null,
    }
  ];

  await db.insert(messages).values(mockMessages);

  console.log("✅ Messages seeded:", mockMessages.length);
  console.log("🎉 Seed complete!");
}

seed().catch(console.error);
